server:
  #端口号
  port: 7970
  servlet:
    context-path: /lcnTx
spring:
  application:
    name: inter-hsp-lcn
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://hsp-rds.wkmhs.com:3306/internethsp?characterEncoding=UTF-8&useUnicode=true&useSSL=true&serverTimezone=UTC
    username: internethsp
    password: Internethsp@2020
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: update
  #redis host名字
  redis:
    host: hsp-redis.wkmhs.com
    #redis端口号
    port: 6379
    #redis 密码
    password: Wkhsp@2020!@
  # 心跳检测时间(ms). 默认为 30000
tx-lcn:
  manager:
    heart-time: 30000
    # 分布式事务执行总时间(ms). 默认为36000
    dtx-time: 8000

    # 事务处理并发等级. 默认为机器逻辑核心数5倍
    concurrent-level: 160
    # 分布式事务锁超时时间 默认为-1，当-1时会用tx-lcn.manager.dtx-time的时间
    dtx-lock-time: ${tx-lcn.manager.dtx-time}

    # 雪花算法的sequence位长度，默认为12位.
    seq-len: 12

    # 异常回调开关。开启时请制定ex-url
    ex-url-enabled: false

    # TM后台登陆密码，默认值为123456
    admin-key: 123456
    #注册中心配置
    #邮箱配置
    #tx-lcn.manager.ex-url=/provider/email-to/18628960476@163.com
    #TM监听IP. 默认为 127.0.0.1
    host: 127.0.0.1
    #TM监听
    port: 8070

  # 开启日志,默认为false
  logger:
    enabled: true
    driver-class-name: ${spring.datasource.driver-class-name}
    jdbc-url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
logging:
  level:
    com:
      codingapi:
        txlcn: DEBUG
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:9092/eureka/eureka
    enabled: true




#spring.mail.host=smtp.163.com
#spring.mail.port=587
#spring.mail.username=18628960476@163.com
#spring.mail.password=334353
