
server:
  #端口号
  port: 9044
  servlet:
    context-path: /webApi
  jetty:
  ####Jetty properties########
    acceptors: 2 # acceptor线程数
    max-http-post-size: 0 # put或post方法最大字节数
    selectors: 4 # selector线程数
##数据库连接信息
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: inter-hsp-webapi
  datasource:
    url: jdbc:mysql://hsp-rds.wkmhs.com:3306/internethsp?characterEncoding=UTF-8&useUnicode=true&useSSL=true&serverTimezone=UTC
    username: internethsp
    password: Internethsp@2020
    driver-class-name: com.mysql.jdbc.Driver
    ###################以下为druid增加的配置###########################
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
    filters:
      commons-log.connection-logger-name: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
    suffix: .html
    mvc:
     static-path-pattern: /**
    resources:
     static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
    prefix: classpath:/templates/

  #JPA配置
  jpa:
    database: mysql
    show-sql: true
    #Hibernate ddl auto
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc:
          lob:
            non_contextual_creation: true
  redis:
    host: hsp-redis.wkmhs.com
    port: 6379
    timeout: 20000
    #    集群环境打开下面注释，单机不需要打开
    #    cluster:
    #      集群信息
    #      nodes: xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx
    #      #默认值是5 一般当此值设置过大时，容易报：Too many Cluster redirections
    #      maxRedirects: 3
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    password: Wkhsp@2020!@


#http client配置服务
http:
  #最大连接数
  maxTotal: 9
  #并发数
  defaultMaxPerRoute: 20
  #创建连接的最长时间
  connectTimeout: 1000
  #从连接池中获取到连接的最长时间
  connectionRequestTimeout: 500
  #数据传输的最长时间
  socketTimeout: 10000
  #提交请求前测试连接是否可用
  staleConnectionCheckEnabled: true
#用户下最多绑定的就诊人数量
params:
  bindPatients: 10

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:9092/eureka/eureka
#      http://localhost:9092/eureka/
      #开启熔断
feign:
  client:
    config:
      default:
        connectTimeout: 100000  #设置httpclient链接超时时间
        readTimeout: 100000   #设置httpclient响应超时时间
  hystrix:
    enabled: true
   


## 这个要有，如果不加，只加了上面也没用
ribbon:
  eureka:
    enabled: true
    ReadTimeout: 10000    #设置httpclient响应超时时间
    ConnectTimeout: 30000    #设置httpclient链接超时时间
    MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
    MaxAutoRetriesNextServer: 0 #重试负载均衡其他的实例最大重试次数,不包括首次调用
    OkToRetryOnAllOperations: true  #是否所有操作都重试

hystrix:
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 50000    #短路多久以后开始尝试是否恢复，默认5s
      execution:
        #timeout:
         # enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 45000     #超时时间（默认为1000ms）
          strategy: SEMAPHORE             #设置在调用线程上执行，并发请求受限于信号量计数


tx-lcn:
  client:
    manager-address: 127.0.0.1:8070
  ribbon:
    loadbalancer:
      dtx:
        enabled: true
  logger:
    enabled: true
    driver-class-name: ${spring.datasource.driver-class-name}
    jdbc-url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
logging:
  level:
    com:
      codingapi:
        txlcn: DEBUG
    org:
      springframework:
        security:
          oauth2: debug  
 #security权限认证配置          
security:
  oauth2:
    resource:
      jwt:
        key-value: client-secret
#  http://boss-beta.wkmhs.com/webApi/refund/orderRefundNotify 测试
#  http://boss-dev.wkmhs.com/webApi/refund/orderRefundNotify 开发
#  http://www.cqmbyy120.cn/webApi/refund/orderRefundNotify
notifyUrl:
  refundUrl: https://boss-prod.wkmhs.com/webApi/refund/orderRefundNotify
oauth:
  tokenUrl: http://boss-prod.wkmhs.com/Oauth/oauth/token
followUp:
  url: https://h5-prod.wkmhs.com
  templateId: 7kZ29gFPMYFpyxbWUzA66GQ07YO-i-dX4cj5yY8lztw #随访提醒模板 api
  templateOrderId: GxNWYOkdXsqhAcJli1ZKDlTlW2IOiRI0L6y_EpF0EX0 #订单待支付提醒模板 api
  templatePrescriptionNotPayId: 3PQKdrQ2GzXzwUPQ1oYuoWhRABThSrt-kED8Wai08GI #处方待支付提醒模板 api
  templatePatientReportId: ykXl7vlB1wiZpwBMok7PjsY7DMEOeSSP-mSCFmsxN1k #患者报道通知模块 api
  templatePrescriptionId: 5uqSwzYfPtSGCP2mVVsrF7I-gs1S8Du2NEbfXY_7Jf8 #处方审核通过提醒模板/处方生成通知模板 doctor/api
  templatePrescriptionCreateId: EEdMNqs0b2gi2DYPCmu40TFJ0V1xPS5wI_M-4q5-KMo #处方生成提醒模板 暂未使用
  templateRemarkId: 1rvbs-Nh1fdVJD9vbVDJMiUIoHt2PgntGbbaLvK1anI #关注成功模板 暂未使用
  templatePushId: oKwVGNuKMiLrcIe64h2cM7BFBZnJbW51W37OfNNpGz8 #订单支付成功提醒模板 暂未使用
  taskTime: 15
